# Generated by Django 4.2.3 on 2023-07-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('depoimento', models.CharField(max_length=100)),
                ('nome_pessoa', models.CharField(max_length=30)),
            ],
        ),
    ]
