# Generated by Django 4.2.3 on 2023-07-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('nome_destino', models.CharField(max_length=30)),
                ('preco', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='depoimento',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
