# Generated by Django 4.2.3 on 2023-08-08 13:28

from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_destino_alter_depoimento_depoimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='foto',
        ),
        migrations.AddField(
            model_name='destino',
            name='descricao',
            field=models.TextField(blank=True, default=None, max_length=200, null=None),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to=trips.models.Destino.upload_foto_destino_1),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to=trips.models.Destino.upload_foto_destino_2),
        ),
        migrations.AddField(
            model_name='destino',
            name='meta',
            field=models.CharField(default=None, max_length=160),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(blank=True, upload_to=trips.models.Depoimento.upload_foto_depoimento),
        ),
    ]
